yarnPath: "/Users/zachwegrzyniak/node-test/.yarn/releases/yarn-berry.js"
packageExtensions:
  sax@*:
    optionalDependencies:
      stream: "*"
  xml2js@*:
    optionalDependencies:
      stream: "*"
      string_decoder: "*"
      timers: "*"
